from datetime import date, datetime, time, timedelta, timezone
from uuid import UUID
from zoneinfo import ZoneInfo

from app.availability.exceptions.repository import AvailabilityExceptionRepository
from app.availability.repository import AvailabilityRepository
from app.core.exceptions.base import (
    NotFoundException,
    ValidationException,
)
from app.core.logging import get_logger
from app.event_types.repository import EventTypeRepository
from app.slots.enums import SlotStatus
from app.slots.model import Slot
from app.slots.repository import SlotRepository
from app.slots.schema import (
    GenerateSlotsRequest,
    SlotGenerationResponse,
    SlotRegenerationResponse,
)
from app.slots.slot_generation import (
    AvailabilityRule,
    EventTypeSpec,
    ExceptionKind,
    ExceptionRule,
    SlotGenerationEngine,
    TimeWindow,
    exclude_overlapping_booked,
)
from app.users.repository import UserRepository

logger = get_logger(__name__)

# Number of host-local calendar days generated by default (ADR-009/021).
SLOT_GENERATION_DAYS = 30


logger = get_logger(__name__)


class SlotService:

    def __init__(
        self,
        slot_repository: SlotRepository,
        event_type_repository: EventTypeRepository,
        availability_repository: AvailabilityRepository,
        availability_exception_repository: AvailabilityExceptionRepository,
        user_repository: UserRepository,
        generation_engine: SlotGenerationEngine,
    ) -> None:
        self.slot_repository = slot_repository
        self.event_type_repository = event_type_repository
        self.availability_repository = availability_repository
        self.availability_exception_repository = availability_exception_repository
        self.user_repository = user_repository
        self.generation_engine = generation_engine

    async def generate_slots(
        self,
        request: GenerateSlotsRequest,
    ) -> SlotGenerationResponse:

        logger.info(
            "Starting slot generation for event type %s "
            "from %s to %s.",
            request.event_type_id,
            request.start_date,
            request.end_date,
        )

        event_type = await self.event_type_repository.find_by_id(
            request.event_type_id,
        )

        if event_type is None:
            logger.warning(
                "Event type %s not found.",
                request.event_type_id,
            )

            raise NotFoundException(
                "Event type not found.",
            )

        if not event_type.is_active:
            logger.warning(
                "Attempted slot generation for inactive "
                "event type %s.",
                event_type.id,
            )

            return SlotGenerationResponse(
                event_type_id=event_type.id,
                start_date=request.start_date,
                end_date=request.end_date,
                generated_count=0,
                skipped_count=0,
                slots=[],
            )

        host = await self.user_repository.find_by_id(
            event_type.host_id,
        )

        if host is None:
            logger.error(
                "Host %s for event type %s was not found.",
                event_type.host_id,
                event_type.id,
            )

            raise NotFoundException(
                "Event type host not found.",
            )

        availability = (
            await self.availability_repository.find_week_schedule(
                event_type.host_id,
            )
        )

        if not availability:
            logger.info(
                "No availability found for host %s.",
                event_type.host_id,
            )

            return SlotGenerationResponse(
                event_type_id=event_type.id,
                start_date=request.start_date,
                end_date=request.end_date,
                generated_count=0,
                skipped_count=0,
                slots=[],
            )

        candidates = self.generation_engine.generate(
            event_type=event_type,
            availability=availability,
            start_date=request.start_date,
            end_date=request.end_date,
            timezone=host.timezone,
        )

        if not candidates:
            logger.info(
                "No slot candidates generated for event type %s.",
                event_type.id,
            )

            return SlotGenerationResponse(
                event_type_id=event_type.id,
                start_date=request.start_date,
                end_date=request.end_date,
                generated_count=0,
                skipped_count=0,
                slots=[],
            )

        range_start = candidates[0].start_at
        range_end = candidates[-1].end_at

        existing_slots = (
            await self.slot_repository
            .find_by_event_type_in_range(
                event_type_id=event_type.id,
                start_at=range_start,
                end_at=range_end,
            )
        )

        existing_by_start = {
            slot.start_at: slot
            for slot in existing_slots
        }

        new_slots: list[Slot] = []
        skipped_count = 0

        for candidate in candidates:

            if candidate.start_at in existing_by_start:
                skipped_count += 1
                continue

            new_slots.append(
                Slot(
                    host_id=event_type.host_id,
                    event_type_id=event_type.id,
                    start_at=candidate.start_at,
                    end_at=candidate.end_at,
                )
            )

        saved_slots = await self.slot_repository.save_many(
            new_slots,
        )

        logger.info(
            "Slot generation completed for event type %s. "
            "Generated=%s, skipped=%s.",
            event_type.id,
            len(saved_slots),
            skipped_count,
        )

        return SlotGenerationResponse(
            event_type_id=event_type.id,
            start_date=request.start_date,
            end_date=request.end_date,
            generated_count=len(saved_slots),
            skipped_count=skipped_count,
            slots=saved_slots,
        )

    # ------------------------------------------------------------------
    # S2-B: host-wide regeneration with reconciliation (ADR-021).
    # ------------------------------------------------------------------
    async def regenerate_host_slots(
        self,
        host_id: UUID,
        from_date: date | None = None,
        to_date: date | None = None,
    ) -> SlotRegenerationResponse:

        logger.info(
            "Starting slot regeneration for host %s (from=%s, to=%s).",
            host_id,
            from_date,
            to_date,
        )

        # 1. Resolve the host (404 if missing).
        host = await self.user_repository.find_by_id(
            host_id,
        )

        if host is None:
            logger.warning(
                "Host %s not found. Rejecting regeneration.",
                host_id,
            )

            raise NotFoundException(
                "Host not found.",
            )

        # 2. Resolve the generation range in host-local calendar time, then
        #    convert to UTC at the persistence boundary (ADR-009/021).
        tz = ZoneInfo(host.timezone)
        local_today = datetime.now(tz).date()

        from_local = from_date or local_today
        to_local = to_date or (
            from_local + timedelta(days=SLOT_GENERATION_DAYS - 1)
        )

        if from_local > to_local:
            raise ValidationException(
                "from_date cannot be after to_date.",
            )

        range_start_utc = datetime.combine(
            from_local,
            time.min,
            tzinfo=tz,
        ).astimezone(timezone.utc)

        range_end_utc = datetime.combine(
            to_local + timedelta(days=1),
            time.min,
            tzinfo=tz,
        ).astimezone(timezone.utc)

        # 3. Load data sequentially on the request session (ADR-010).
        availability = (
            await self.availability_repository.find_week_schedule(
                host_id,
            )
        )

        exceptions = (
            await self.availability_exception_repository
            .find_for_host_and_range(
                host_id,
                from_local,
                to_local,
            )
        )

        event_types = await self.event_type_repository.list_by_host(
            host_id,
        )

        existing_slots = (
            await self.slot_repository.find_by_host_starting_in_range(
                host_id=host_id,
                start_at=range_start_utc,
                end_at=range_end_utc,
            )
        )

        booked_slots = (
            await self.slot_repository.find_booked_by_host_in_range(
                host_id=host_id,
                start_at=range_start_utc,
                end_at=range_end_utc,
            )
        )

        # 4. Map ORM rows to pure engine inputs (the engine stays ORM-free).
        rules = [
            AvailabilityRule(
                day_of_week=item.day_of_week,
                start_time=item.start_time,
                end_time=item.end_time,
                is_available=item.is_available,
            )
            for item in availability
        ]

        pure_exceptions = [
            ExceptionRule(
                kind=ExceptionKind[exc.kind.name],
                date=exc.exception_date,
                start_time=exc.start_time,
                end_time=exc.end_time,
            )
            for exc in exceptions
        ]

        event_type_by_id = {
            event_type.id: event_type
            for event_type in event_types
        }

        # 5. BOOKED slots, expanded by their own event type's buffers into UTC
        #    occupied windows (ADR-008). Only BOOKED slots collide.
        booked_windows: list[TimeWindow] = []
        for slot in booked_slots:
            event_type = event_type_by_id.get(
                slot.event_type_id,
            )

            buffer_before = (
                event_type.buffer_before_minutes
                if event_type is not None
                else 0
            )
            buffer_after = (
                event_type.buffer_after_minutes
                if event_type is not None
                else 0
            )

            booked_windows.append(
                TimeWindow(
                    start=slot.start_at
                    - timedelta(minutes=buffer_before),
                    end=slot.end_at
                    + timedelta(minutes=buffer_after),
                )
            )

        # 6. Generate candidates per event type (each has its own duration and
        #    buffers), filter past slots, and exclude booked collisions.
        now_utc = datetime.now(timezone.utc)
        candidate_keys: set[tuple[UUID, datetime, datetime]] = set()

        for event_type in event_types:

            if not event_type.is_active:
                continue

            spec = EventTypeSpec(
                duration_minutes=event_type.duration_minutes,
                buffer_before_minutes=event_type.buffer_before_minutes,
                buffer_after_minutes=event_type.buffer_after_minutes,
            )

            candidates = self.generation_engine.generate(
                event_type=spec,
                availability=rules,
                exceptions=pure_exceptions,
                start_date=from_local,
                end_date=to_local,
                timezone=host.timezone,
            )

            candidates = [
                candidate
                for candidate in candidates
                if candidate.start_at.astimezone(timezone.utc) > now_utc
            ]

            candidates = exclude_overlapping_booked(
                candidates,
                spec,
                booked_windows,
            )

            for candidate in candidates:
                candidate_keys.add(
                    (
                        event_type.id,
                        candidate.start_at.astimezone(timezone.utc),
                        candidate.end_at.astimezone(timezone.utc),
                    )
                )

        # 7. Reconcile (ADR-011/012): insert missing, restore stale BLOCKED,
        #    block obsolete AVAILABLE/BLOCKED, never touch BOOKED.
        existing_by_key = {
            (slot.event_type_id, slot.start_at, slot.end_at): slot
            for slot in existing_slots
        }

        to_insert: list[Slot] = []
        restore_ids: list[UUID] = []
        blocked_ids: list[UUID] = []
        kept_count = 0
        booked_count = 0

        for key in candidate_keys:
            existing = existing_by_key.get(key)

            if existing is None:
                to_insert.append(
                    Slot(
                        host_id=host_id,
                        event_type_id=key[0],
                        start_at=key[1],
                        end_at=key[2],
                    )
                )
            elif existing.status == SlotStatus.BOOKED:
                booked_count += 1
            elif existing.status == SlotStatus.BLOCKED:
                restore_ids.append(existing.id)
            else:
                kept_count += 1

        for slot in existing_slots:
            key = (slot.event_type_id, slot.start_at, slot.end_at)

            if key in candidate_keys:
                continue

            if slot.status == SlotStatus.BOOKED:
                booked_count += 1
            else:
                blocked_ids.append(slot.id)

        generated_count = await self.slot_repository.insert_many_on_conflict_do_nothing(
            to_insert,
        )

        restored_count = await self.slot_repository.set_status_conditional(
            restore_ids,
            SlotStatus.AVAILABLE,
        )

        blocked_count = await self.slot_repository.set_status_conditional(
            blocked_ids,
            SlotStatus.BLOCKED,
        )

        logger.info(
            "Regeneration completed for host %s: generated=%s, "
            "restored=%s, blocked=%s, kept=%s, booked=%s.",
            host_id,
            generated_count,
            restored_count,
            blocked_count,
            kept_count,
            booked_count,
        )

        return SlotRegenerationResponse(
            host_id=host_id,
            from_date=from_local,
            to_date=to_local,
            timezone=host.timezone,
            generated_count=generated_count,
            restored_count=restored_count,
            blocked_count=blocked_count,
            kept_count=kept_count,
            booked_count=booked_count,
        )