"""Create bookings table

Revision ID: 5dba780ddb08
Revises: 8259d7d315b1
Create Date: 2026-08-09 00:11:19.147876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dba780ddb08'
down_revision: Union[str, Sequence[str], None] = '8259d7d315b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('attendee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_attendee_id', 'bookings', ['attendee_id'], unique=False)
    op.create_index('ix_bookings_host_id', 'bookings', ['host_id'], unique=False)
    op.create_index('ix_bookings_slot_id', 'bookings', ['slot_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_slot_id', table_name='bookings')
    op.drop_index('ix_bookings_host_id', table_name='bookings')
    op.drop_index('ix_bookings_attendee_id', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
