"""create slots table

Revision ID: 8259d7d315b1
Revises: 0a11dcbb89b9
Create Date: 2026-08-08 22:52:56.692771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8259d7d315b1'
down_revision: Union[str, Sequence[str], None] = '0a11dcbb89b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'BLOCKED', name='slotstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'start_at', 'end_at', name='uq_slot_event_type_start_end')
    )
    op.create_index(op.f('ix_slots_event_type_id'), 'slots', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_slots_host_id'), 'slots', ['host_id'], unique=False)
    op.create_index('ix_slots_host_start_at', 'slots', ['host_id', 'start_at'], unique=False)
    op.create_index('ix_slots_status', 'slots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slots_status', table_name='slots')
    op.drop_index('ix_slots_host_start_at', table_name='slots')
    op.drop_index(op.f('ix_slots_host_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_event_type_id'), table_name='slots')
    op.drop_table('slots')
    # ### end Alembic commands ###
