"""create event types table

Revision ID: f73ab469ca3a
Revises: 1385de47e498
Create Date: 2026-08-07 23:16:59.971939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73ab469ca3a'
down_revision: Union[str, Sequence[str], None] = '1385de47e498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('location_value', sa.String(length=255), nullable=True),
    sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'slug', name='uq_event_type_host_slug')
    )
    op.create_index(op.f('ix_event_types_host_id'), 'event_types', ['host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_types_host_id'), table_name='event_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
